///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Jenkins
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the JenkinsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("54156ae1-b43e-4392-885a-e16fdbc71d96")]
    public partial class JenkinsRepository : RepoGenBaseFolder
    {
        static JenkinsRepository instance = new JenkinsRepository();
        JenkinsRepositoryFolders.Form1ReminderAppFolder _form1reminder;
        JenkinsRepositoryFolders.FormVipApplicationAppFolder _formvipapplication;

        /// <summary>
        /// Gets the singleton class instance representing the JenkinsRepository element repository.
        /// </summary>
        [RepositoryFolder("54156ae1-b43e-4392-885a-e16fdbc71d96")]
        public static JenkinsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public JenkinsRepository() 
            : base("JenkinsRepository", "/", null, 0, false, "54156ae1-b43e-4392-885a-e16fdbc71d96", ".\\RepositoryImages\\JenkinsRepository54156ae1.rximgres")
        {
            _form1reminder = new JenkinsRepositoryFolders.Form1ReminderAppFolder(this);
            _formvipapplication = new JenkinsRepositoryFolders.FormVipApplicationAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("54156ae1-b43e-4392-885a-e16fdbc71d96")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Form1Reminder folder.
        /// </summary>
        [RepositoryFolder("5c6f01da-a72a-44cc-84f7-5ba52df14458")]
        public virtual JenkinsRepositoryFolders.Form1ReminderAppFolder Form1Reminder
        {
            get { return _form1reminder; }
        }

        /// <summary>
        /// The FormVipApplication folder.
        /// </summary>
        [RepositoryFolder("2c553187-492c-49a2-81b3-f1311851f33a")]
        public virtual JenkinsRepositoryFolders.FormVipApplicationAppFolder FormVipApplication
        {
            get { return _formvipapplication; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class JenkinsRepositoryFolders
    {
        /// <summary>
        /// The Form1ReminderAppFolder folder.
        /// </summary>
        [RepositoryFolder("5c6f01da-a72a-44cc-84f7-5ba52df14458")]
        public partial class Form1ReminderAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttondismissInfo;
            RepoItemInfo _titlebar1reminderInfo;

            /// <summary>
            /// Creates a new Form1Reminder  folder.
            /// </summary>
            public Form1ReminderAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form1Reminder", "/form[@title='1 Reminder']", parentFolder, 30000, null, true, "5c6f01da-a72a-44cc-84f7-5ba52df14458", "")
            {
                _buttondismissInfo = new RepoItemInfo(this, "ButtonDismiss", "button[@text='&Dismiss']", 30000, null, "b9899e26-8648-4d3b-8e3c-66ccc75bb5d2");
                _titlebar1reminderInfo = new RepoItemInfo(this, "TitleBar1Reminder", "titlebar[@accessiblerole='TitleBar']", 30000, null, "593f8001-114f-43ce-ba23-7b899f5aba32");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5c6f01da-a72a-44cc-84f7-5ba52df14458")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5c6f01da-a72a-44cc-84f7-5ba52df14458")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonDismiss item.
            /// </summary>
            [RepositoryItem("b9899e26-8648-4d3b-8e3c-66ccc75bb5d2")]
            public virtual Ranorex.Button ButtonDismiss
            {
                get
                {
                    return _buttondismissInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonDismiss item info.
            /// </summary>
            [RepositoryItemInfo("b9899e26-8648-4d3b-8e3c-66ccc75bb5d2")]
            public virtual RepoItemInfo ButtonDismissInfo
            {
                get
                {
                    return _buttondismissInfo;
                }
            }

            /// <summary>
            /// The TitleBar1Reminder item.
            /// </summary>
            [RepositoryItem("593f8001-114f-43ce-ba23-7b899f5aba32")]
            public virtual Ranorex.TitleBar TitleBar1Reminder
            {
                get
                {
                    return _titlebar1reminderInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The TitleBar1Reminder item info.
            /// </summary>
            [RepositoryItemInfo("593f8001-114f-43ce-ba23-7b899f5aba32")]
            public virtual RepoItemInfo TitleBar1ReminderInfo
            {
                get
                {
                    return _titlebar1reminderInfo;
                }
            }
        }

        /// <summary>
        /// The FormVipApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("2c553187-492c-49a2-81b3-f1311851f33a")]
        public partial class FormVipApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _musicInfo;
            RepoItemInfo _rbmaleInfo;
            RepoItemInfo _btaddInfo;
            RepoItemInfo _btdeleteInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new FormVipApplication  folder.
            /// </summary>
            public FormVipApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormVipApplication", "/form[@controlname='formVipApplication']", parentFolder, 30000, null, true, "2c553187-492c-49a2-81b3-f1311851f33a", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First Name:']", 30000, null, "d9430882-3785-4749-bfaa-a7771dc85783");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last Name:']", 30000, null, "ec444731-e13f-46ad-b36d-c8a8f30b4fb6");
                _musicInfo = new RepoItemInfo(this, "Music", "list[@controlname='lbCategory']/?/?/listitem[@accessiblename='Music']", 30000, null, "9e032e5e-83fb-458d-8f6b-4df2e8a4fe9d");
                _rbmaleInfo = new RepoItemInfo(this, "RbMale", "?/?/radiobutton[@controlname='rbMale']", 30000, null, "a7050024-f927-440c-a6c6-32b58ceeeb4c");
                _btaddInfo = new RepoItemInfo(this, "BtAdd", "button[@controlname='btAdd']", 30000, null, "c3f1bec8-44f6-427b-9148-dffa4cb86f23");
                _btdeleteInfo = new RepoItemInfo(this, "BtDelete", "button[@controlname='btDelete']", 30000, null, "f5109b06-0956-41ad-b452-d32aa1d95a7e");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "5c0161a1-a913-4d98-af93-73ee768c0c6e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2c553187-492c-49a2-81b3-f1311851f33a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2c553187-492c-49a2-81b3-f1311851f33a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("d9430882-3785-4749-bfaa-a7771dc85783")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("d9430882-3785-4749-bfaa-a7771dc85783")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("ec444731-e13f-46ad-b36d-c8a8f30b4fb6")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("ec444731-e13f-46ad-b36d-c8a8f30b4fb6")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Music item.
            /// </summary>
            [RepositoryItem("9e032e5e-83fb-458d-8f6b-4df2e8a4fe9d")]
            public virtual Ranorex.ListItem Music
            {
                get
                {
                    return _musicInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Music item info.
            /// </summary>
            [RepositoryItemInfo("9e032e5e-83fb-458d-8f6b-4df2e8a4fe9d")]
            public virtual RepoItemInfo MusicInfo
            {
                get
                {
                    return _musicInfo;
                }
            }

            /// <summary>
            /// The RbMale item.
            /// </summary>
            [RepositoryItem("a7050024-f927-440c-a6c6-32b58ceeeb4c")]
            public virtual Ranorex.RadioButton RbMale
            {
                get
                {
                    return _rbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RbMale item info.
            /// </summary>
            [RepositoryItemInfo("a7050024-f927-440c-a6c6-32b58ceeeb4c")]
            public virtual RepoItemInfo RbMaleInfo
            {
                get
                {
                    return _rbmaleInfo;
                }
            }

            /// <summary>
            /// The BtAdd item.
            /// </summary>
            [RepositoryItem("c3f1bec8-44f6-427b-9148-dffa4cb86f23")]
            public virtual Ranorex.Button BtAdd
            {
                get
                {
                    return _btaddInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtAdd item info.
            /// </summary>
            [RepositoryItemInfo("c3f1bec8-44f6-427b-9148-dffa4cb86f23")]
            public virtual RepoItemInfo BtAddInfo
            {
                get
                {
                    return _btaddInfo;
                }
            }

            /// <summary>
            /// The BtDelete item.
            /// </summary>
            [RepositoryItem("f5109b06-0956-41ad-b452-d32aa1d95a7e")]
            public virtual Ranorex.Button BtDelete
            {
                get
                {
                    return _btdeleteInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtDelete item info.
            /// </summary>
            [RepositoryItemInfo("f5109b06-0956-41ad-b452-d32aa1d95a7e")]
            public virtual RepoItemInfo BtDeleteInfo
            {
                get
                {
                    return _btdeleteInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("5c0161a1-a913-4d98-af93-73ee768c0c6e")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("5c0161a1-a913-4d98-af93-73ee768c0c6e")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}